### ISSUE TITLE
有什么例子么？

### ISSUE THREAD

**Issue by GC-ZF** [A-kirami/nonebot-plugin-answersbook#1]
我的返回不了答案，是不是我发送的消息有问题？
![image](https://user-images.githubusercontent.com/94956933/174938686-78bfd156-30ef-48d8-8ddf-14f3a4c0c574.png)

**Comment by A-kirami** [comment]
目前仅限群聊使用

**Comment by GC-ZF** [comment]
> 目前仅限群聊使用

ok，谢谢你
